name: user_app
description: Jeb Dekho user application for accessing transport, food, and mart services.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.0.0
  http: ^1.1.0
  socket_io_client: ^2.0.3
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true